ORG = "VATEUD"
RSS_NEW = "http://feeds.feedburner.com/VateudNewTasks"
RSS_COMPLETED = "http://feeds.feedburner.com/VateudCompletedTasks"
RSS_COMMENTS = "http://feeds.feedburner.com/VateudLatestComments"
LOGO_IMAGE = "vateud_png.png"